/** Stable permission keys for the matrix + enforcement. */
export const PERMISSION_KEYS = [
  "org.group.read",
  "org.group.update",
  "company.create",
  "company.read",
  "company.update",
  "company.archive",
  "company.restore",
  "company.soft_delete",
  "company.purge",
  "project.create",
  "project.read",
  "project.update",
  "project.archive",
  "project.restore",
  "project.soft_delete",
  "project.purge",
  "project.workflow.read",
  "project.workflow.update",
  "project.map.update",
  "project.member.manage",
  "recognition.read",
  "recognition.create",
  "feedback.submit",
  "feedback.read",
  "leaderboard.read",
  "knowledge.read",
  "knowledge.create",
  "staff.create",
  "staff.read",
  "staff.update",
  "staff.assign_company",
  "staff.assign_project",
  "staff.soft_delete",
  "staff.restore",
  "staff.purge",
  "role.display_name.update",
  "permission.matrix.read",
  "permission.matrix.update",
  "trash.read",
  "trash.restore",
  "trash.purge",
  "lifecycle.onboarding.skip",
  "lifecycle.onboarding.hub",
  "lifecycle.hr.pipeline",
  "lifecycle.email.send",
] as const;

export type PermissionKey = (typeof PERMISSION_KEYS)[number];

export const ALL_PERMISSION_KEYS: Set<string> = new Set(PERMISSION_KEYS);
